version: "3.9"

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: jollibee-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: jollibee-kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"

  menu-service:
    build: ./menu-service
    container_name: menu-service
    env_file:
      - ./menu-service/.env
    depends_on:
      - kafka
    volumes:
      - ./menu-service/src/database:/usr/src/app/src/database
    ports:
      - "3001:3001"

  cart-service:
    build: ./cart-service
    container_name: cart-service
    env_file:
      - ./cart-service/.env
    depends_on:
      - kafka
    volumes:
      - ./cart-service/src/database:/usr/src/app/src/database
    ports:
      - "3002:3002"

  order-service:
    build: ./order-service
    container_name: order-service
    env_file:
      - ./order-service/.env
    depends_on:
      - kafka
    volumes:
      - ./order-service/src/database:/usr/src/app/src/database
    ports:
      - "3003:3003"

  payment-service:
    build: ./payment-service
    container_name: payment-service
    env_file:
      - ./payment-service/.env
    depends_on:
      - kafka
    volumes:
      - ./payment-service/src/database:/usr/src/app/src/database
    ports:
      - "3004:3004"

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    depends_on:
      - menu-service
      - cart-service
      - order-service
      - payment-service
    ports:
      - "8080:80"

  client:
    build: ./client
    container_name: jollibee-client
    depends_on:
      - api-gateway
    ports:
      - "3000:80"
