version: "3.9"

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: jollibee-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: jollibee-kafka
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper

  menu-service:
    build: ./menu-service
    container_name: menu-service
    ports:
      - "3001:3001"
    env_file: ./menu-service/.env
    environment:
      KAFKA_BROKER: kafka:9092
    depends_on:
      - kafka
    volumes:
      - ./menu-service/src/database:/usr/src/app/src/database

  cart-service:
    build: ./cart-service
    container_name: cart-service
    ports:
      - "3002:3002"
    env_file: ./cart-service/.env
    environment:
      KAFKA_BROKER: kafka:9092
    depends_on:
      - kafka
    volumes:
      - ./cart-service/src/database:/usr/src/app/src/database

  order-service:
    build: ./order-service
    container_name: order-service
    ports:
      - "3003:3003"
    env_file: ./order-service/.env
    environment:
      KAFKA_BROKER: kafka:9092
    depends_on:
      - kafka
    volumes:
      - ./order-service/src/database:/usr/src/app/src/database

  payment-service:
    build: ./payment-service
    container_name: payment-service
    ports:
      - "3004:3004"
    env_file: ./payment-service/.env
    environment:
      KAFKA_BROKER: kafka:9092
    depends_on:
      - kafka
    volumes:
      - ./payment-service/src/database:/usr/src/app/src/database

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "8080:80"
    depends_on:
      - menu-service
      - cart-service
      - order-service
      - payment-service
